server:
  port: ${PORT:8080}   # Render sets PORT

spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}   # Default to dev, override in env

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
